// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef QUOKKA_RV_REGS_H
#define QUOKKA_RV_REGS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <assert.h>

// Mem - m_data_mem
typedef struct __attribute__ ((__packed__)) {
    uint32_t mem[16384];
} m_data_mem_t;

// Reg - char_display::r_char_mem
#define CHAR_DISPLAY__R_CHAR_MEM__CHAR_bm 0xff
#define CHAR_DISPLAY__R_CHAR_MEM__CHAR_bp 0
#define CHAR_DISPLAY__R_CHAR_MEM__CHAR_bw 8

// Reg - char_display::r_colour
#define CHAR_DISPLAY__R_COLOUR__RED_bm 0xff
#define CHAR_DISPLAY__R_COLOUR__RED_bp 0
#define CHAR_DISPLAY__R_COLOUR__RED_bw 8
#define CHAR_DISPLAY__R_COLOUR__GREEN_bm 0xff00
#define CHAR_DISPLAY__R_COLOUR__GREEN_bp 8
#define CHAR_DISPLAY__R_COLOUR__GREEN_bw 8
#define CHAR_DISPLAY__R_COLOUR__BLUE_bm 0xff0000
#define CHAR_DISPLAY__R_COLOUR__BLUE_bp 16
#define CHAR_DISPLAY__R_COLOUR__BLUE_bw 8

// Addrmap - char_display
typedef struct __attribute__ ((__packed__)) {
    uint8_t char_mem[2400];
    uint8_t RESERVED_960_7fff[0x76a0];
    uint32_t font_colour;
    uint32_t background_colour;
} char_display_t;

// Reg - riscv_timer::r_timer
#define RISCV_TIMER__R_TIMER__TIMER_bm 0xffffffff
#define RISCV_TIMER__R_TIMER__TIMER_bp 0
#define RISCV_TIMER__R_TIMER__TIMER_bw 32

// Reg - riscv_timer::r_timer_cmp
#define RISCV_TIMER__R_TIMER_CMP__TIMER_CMP_bm 0xffffffff
#define RISCV_TIMER__R_TIMER_CMP__TIMER_CMP_bp 0
#define RISCV_TIMER__R_TIMER_CMP__TIMER_CMP_bw 32

// Addrmap - riscv_timer
typedef struct __attribute__ ((__packed__)) {
    uint32_t mtime;
    uint32_t mtimeh;
    uint32_t mtimecmp;
    uint32_t mtimecmph;
} riscv_timer_t;

// Reg - interrupt_controller::r_enable
#define INTERRUPT_CONTROLLER__R_ENABLE__ENABLE_bm 0xffffffff
#define INTERRUPT_CONTROLLER__R_ENABLE__ENABLE_bp 0
#define INTERRUPT_CONTROLLER__R_ENABLE__ENABLE_bw 32
#define INTERRUPT_CONTROLLER__R_ENABLE__ENABLE_reset 0x0

// Reg - interrupt_controller::r_pending
#define INTERRUPT_CONTROLLER__R_PENDING__PENDING_bm 0xffffffff
#define INTERRUPT_CONTROLLER__R_PENDING__PENDING_bp 0
#define INTERRUPT_CONTROLLER__R_PENDING__PENDING_bw 32
#define INTERRUPT_CONTROLLER__R_PENDING__PENDING_reset 0x0

// Addrmap - interrupt_controller
typedef struct __attribute__ ((__packed__)) {
    uint32_t enable;
    uint32_t pending;
} interrupt_controller_t;

// Instances
#define data_mem (*(volatile m_data_mem_t *)0x10000000UL)
#define char_display (*(volatile char_display_t *)0x80000000UL)
#define riscv_timer (*(volatile riscv_timer_t *)0x90000000UL)
#define interrupt_controller (*(volatile interrupt_controller_t *)0xa0000000UL)


static_assert(sizeof(m_data_mem_t) == 0x10000, "Packing error");
static_assert(sizeof(char_display_t) == 0x8008, "Packing error");
static_assert(sizeof(riscv_timer_t) == 0x10, "Packing error");
static_assert(sizeof(interrupt_controller_t) == 0x8, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* QUOKKA_RV_REGS_H */
